import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.scss'
import Footer from '@/components/footer/page';

// const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Fabio Enrique Brasil',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="pt-br">
      <body className='h-full relative'>
        {children}
        <Footer />
      </body>
    </html>
  )
}
